### ISSUE TITLE
how to create tcp packet with custom tcp options?

### ISSUE THREAD

**Issue by johnwas** [dotpcap/packetnet#137]
I can create a tcp packet with class TcpPacket by using constructor:
            public TcpPacket(ushort sourcePort, ushort destinationPort)

But if I Change Property OptionsCollection, it will throw exception,  becouse the tcp header's  length is not big enough to hold the options.  Is this a bug or not implemented?

**Comment by PhyxionNL** [comment]
You need to preallocate a buffer large enough to hold the data.

**Comment by mrsleepman** [comment]
I have the same problem. I read the source code but don't understand how to use it. Are there any relevant examples?
