### ISSUE TITLE
IcmpV4Packet doesn't calculate its checksum

### ISSUE THREAD

**Issue by trudyhood** [dotpcap/packetnet#140]
I see IcmpV6Packet automatically calculate its checksum, but IcmpV4Packet doesn't do that. Is that normal?

**Comment by PhyxionNL** [comment]
ICMPv6 shouldn't calculate it checksum either in UpdateCalculatedValues, it should have a separate method to update it just like all the other packets. I'll take this issue @chmorgan.

**Comment by trudyhood** [comment]
So would you please add a utility method to calculate IcmpV6packet checksum?
