### ISSUE TITLE
IcmpV6Packet buffer goes into header

### ISSUE THREAD

**Issue by trudyhood** [dotpcap/packetnet#142]
Maybe I don't know how to use IPv6! I really can't understand how does it work or maybe there are many bugs.

```c#
var buffer = new byte[100];
var icmpPacket = new IcmpV6Packet(new ByteArraySegment(buffer));
```
icmpPacket.HeaderData is 100 bytes!

**Comment by PhyxionNL** [comment]
At the moment there's no header and payload separation for ICMPv6.

**Comment by PhyxionNL** [comment]
This is now separated into header and payload.
