### ISSUE TITLE
sharppcap Windows tests fail

### ISSUE THREAD

**Issue by PhyxionNL** [dotpcap/packetnet#150]
@chmorgan Maybe you can look into this. I'm not using pcap stuff that much, but it works here locally. I'm also wondering whether it needs updating to npcap as winpcap isn't supported anymore.

**Comment by kayoub5** [comment]
winpcap still supported, some tests are disabled in CI if dependent on minimum libpcap version, what tests fail for you?

**Comment by PhyxionNL** [comment]
> 
> 
> winpcap still supported,
On their site: WinPcap Has Ceased Development. We recommend Npcap.

 some tests are disabled in CI if dependent on minimum libpcap version, what tests fail for you?

All fail due to wcap DLL failure, see: https://github.com/chmorgan/packetnet/runs/3777064424?check_suite_focus=true

**Comment by kayoub5** [comment]
github actions Windows virtual environment is not compatible with winpcap or npcap, this is a CI limitation not a library limitation.

**Comment by PhyxionNL** [comment]
> 
> 
> github actions Windows virtual environment is not compatible with winpcap or npcap, this is a CI limitation not a library limitation.

Well, it used to work and weirdly, sometimes it still does: https://github.com/chmorgan/packetnet/runs/3777070826

**Comment by kayoub5** [comment]
could be that winpcap install silently failed.
wpcap not found means no winpcap was found in the system. 
@chmorgan have an oem key for npcap, you may want to try try using that.

**Comment by chmorgan** [comment]
Yeah I can look at pulling that installer script abs secret key over.
Inconsistent CI runs are such a time sink, if npcap resolves that would be
great.

**Comment by alexhiggins732** [comment]
Is this still open? https://github.com/dotpcap/packetnet/actions shows the last 4 build succeeded.

**Comment by PhyxionNL** [comment]
Seems to work again, closing.
