### ISSUE TITLE
LinkLayers have wrong base type

### ISSUE THREAD

**Issue by kayoub5** [dotpcap/packetnet#167]
Currently the `LinkLayers` assumes that it is a single byte, and that max value is 255.

This is not right:
* PCAPNG allocates 2 bytes for the LinkType field https://www.ietf.org/staging/draft-tuexen-opsawg-pcapng-02.html#section_idb
* PCAP format allocates 4 bytes for it https://wiki.wireshark.org/Development/LibpcapFileFormat
* Link type values already reached 292 https://www.tcpdump.org/linktypes.html

# Danger

Changing the base type of this field is a breaking change, that will affect backward compatibility with all dependencies, including but not limited to sharppcap.

**Comment by PhyxionNL** [comment]
Let's follow IETF here and make it to 16 bit. Might be useful to update the link types then as well based on tcpdump / https://datatracker.ietf.org/doc/html/draft-ietf-opsawg-pcap#section-8.2
