### ISSUE TITLE
Add support to NDP

### ISSUE THREAD

**Issue by Ben3094** [dotpcap/packetnet#174]
Hello,
With IPv4 to IPv6 transition, PacketDotNet lost neighbor discovery using ARP. To correct that, why not add NDP (Neighbor Discovery Protocol) to PacketDotNet ?
Thank you in advance,
Best regards,

**Comment by Ben3094** [comment]
You can implement @maxlluky [Mantikor](https://github.com/maxlluky/Mantikor) version to speed up development.

**Comment by PhyxionNL** [comment]
That "implementation" was pretty much nothing, but I have this added in #175.

**Comment by Ben3094** [comment]
Wow!
Thank you 
😊👍
