### ISSUE TITLE
log4net dependency in nuget package

### ISSUE THREAD

**Issue by wo80** [dotpcap/packetnet#181]
Hi.
The latest nuget packages (1.4.5, 1.4.6-pre) have a dependency on log4net. Is this intended? Looking at the [PacketDotNet.csproj](https://github.com/dotpcap/packetnet/blob/master/PacketDotNet/PacketDotNet.csproj#L35) project file, it seems a debug version was published by accident...

**Comment by PhyxionNL** [comment]
I see, that's odd. It should build the release version:
https://github.com/dotpcap/packetnet/blob/master/.github/workflows/master.yml#L70

I've pushed a commit that hopefully addresses it :)

**Comment by PhyxionNL** [comment]
It was because dotnet test was building the debug version, which caused a debug NuGet package to be generated as well. This'll be fixed in #183.

**Comment by wo80** [comment]
Thanks for the quick 1.4.6 release!
