### ISSUE TITLE
CI woes

### ISSUE THREAD

**Issue by PhyxionNL** [dotpcap/packetnet#186]
@chmorgan 
Can you:
- Create a new NuGet key, the current one has expired.
- Remove semaphore and appveyor (it's still there), or give me access to modify that 🙂.

**Comment by chmorgan** [comment]
I’ll take a look at this tonight and make a new key and try to remove the
other CI systems. I think I’d have to add you as a user to semaphore and
appveyor if we went that route but it might not be an option for free
accounts.

**Comment by chmorgan** [comment]
Alright, nuget keys have been updated across all projects.

**Comment by chmorgan** [comment]
Alright, uninstalled circleci, travisci, semaphore, revoked permissions. Anything else to do?

**Comment by PhyxionNL** [comment]
Thanks, testing it #187.

**Comment by PhyxionNL** [comment]
AppVeyor is still running 🤔
continuous-integration/appveyor/branch — AppVeyor build succeeded 
 continuous-integration/appveyor/pr — AppVeyor build succeeded

**Comment by chmorgan** [comment]
@PhyxionNL alright, deleted the appveyor project, that should do it

**Comment by chmorgan** [comment]
@PhyxionNL other projects in the same organization use appveyor still. It can be removed at that layer but it would take it out for all of the other projects.

**Comment by chmorgan** [comment]
And maybe this happened before the internals of appveyor were updated? If you click on the link in #187 you'll go to a 'project not found' page on appveyor.

**Comment by PhyxionNL** [comment]
Can't you remove it at settings/installations and/or settings/hooks page (in project settings)? It should be possible to separate as dotpcap has various others not used here.

**Comment by chmorgan** [comment]
@PhyxionNL its not listed in the webhooks list for the repo. I don't see a settings/installations menu.

Not sure how/why its running.
