### ISSUE TITLE
Move off System.Runtime.CompilerServices.Unsafe nuget?

### ISSUE THREAD

**Issue by tfadler** [dotpcap/packetnet#196]
Hi.  I have a question.

Are there plans to move off the System.Runtime.CompilerServices.Unsafe NuGet package?

New versions will not be created.

See https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/unsafe-package

**Comment by PhyxionNL** [comment]
No, please read what it actually says there.

**Comment by cklogs** [comment]
I'm also curious about the changes to the `Unsafe` nuget. I may be misinterpretting, but can I assume that packetnet won't target versions .NET 7 and beyond?
