### ISSUE TITLE
Consider converting most classes, especially data packet headers, into structures?

### ISSUE THREAD

**Issue by sgf** [dotpcap/packetnet#210]
This is mainly based on GC and performance considerations.

about bit-field ,there was a source generator support that. 
https://github.com/barncastle/BitsKit
This library is almost the best library for bit-field support so far.

**Comment by PhyxionNL** [comment]
Most allocations come from the backing byte array, which is something you can largely avoid. Even with gbit saturated both ways you shouldn't have to run into issues.
